<?php
/**
 * Custom post types for Miracle Mile Shops.
 *
 * Replaces the Custom Post Type UI plugin (removed 2026-09-17). Every argument below is
 * exactly what that plugin passed to register_post_type() at runtime, captured through the
 * register_post_type_args filter, so the registration is identical. Edit here from now on.
 */

function mms_register_post_types() {

	// Jobs
	register_post_type( 'jobs', array(
		'labels' => array(
			'name' => 'Jobs',
			'singular_name' => 'Job',
			'menu_name' => 'Jobs',
			'all_items' => 'All Jobs',
			'add_new_item' => 'Add New Job',
			'edit_item' => 'Edit Job',
			'new_item' => 'New Job',
			'view_item' => 'View Job',
			'view_items' => 'View Jobs',
			'search_items' => 'Search Jobs',
			'not_found' => 'No Jobs Found',
			'not_found_in_trash' => 'No Jobs found in trash.',
		),
		'description' => '',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'has_archive' => false,
		'show_in_menu' => true,
		'delete_with_user' => false,
		'show_in_rest' => true,
		'rest_base' => null,
		'rest_controller_class' => null,
		'rest_namespace' => null,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => null,
		'rewrite' => array(
			'slug' => 'jobs',
			'with_front' => true,
		),
		'menu_position' => 6,
		'menu_icon' => null,
		'register_meta_box_cb' => null,
		'query_var' => true,
		'supports' => array( 'title', 'custom-fields' ),
		'taxonomies' => array( 'category' ),
	) );

	// Shops
	register_post_type( 'shops', array(
		'labels' => array(
			'name' => 'Shops',
			'singular_name' => 'Shop',
			'all_items' => 'All Shops',
			'add_new_item' => 'Add new Shop',
			'edit_item' => 'Edit Shop',
			'new_item' => 'New Shop',
			'view_item' => 'View Shop',
			'view_items' => 'View Shops',
			'search_items' => 'Search Shops',
			'not_found' => 'No Shops found.',
			'not_found_in_trash' => 'No Shops found in trash.',
		),
		'description' => '',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'has_archive' => true,
		'show_in_menu' => true,
		'delete_with_user' => false,
		'show_in_rest' => true,
		'rest_base' => null,
		'rest_controller_class' => null,
		'rest_namespace' => null,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => null,
		'rewrite' => array(
			'slug' => 'shops',
			'with_front' => true,
		),
		'menu_position' => null,
		'menu_icon' => 'dashicons-cart',
		'register_meta_box_cb' => null,
		'query_var' => true,
		'supports' => array( 'title', 'thumbnail', 'custom-fields' ),
		'taxonomies' => array( 'category' ),
	) );

	// Entertainment
	register_post_type( 'entertainment', array(
		'labels' => array(
			'name' => 'Entertainment',
			'singular_name' => 'Entertainment',
			'all_items' => 'All Entertainment',
			'add_new_item' => 'Add new Entertainment',
			'edit_item' => 'Edit Entertainment',
			'new_item' => 'New Entertainment',
			'view_item' => 'View Entertainment',
			'view_items' => 'View Entertainment',
			'search_items' => 'Search Entertainment',
			'not_found' => 'No Entertainment found.',
			'not_found_in_trash' => 'No Entertainment found in trash.',
		),
		'description' => '',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'has_archive' => true,
		'show_in_menu' => true,
		'delete_with_user' => false,
		'show_in_rest' => true,
		'rest_base' => null,
		'rest_controller_class' => null,
		'rest_namespace' => null,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => null,
		'rewrite' => array(
			'slug' => 'entertainment',
			'with_front' => true,
		),
		'menu_position' => null,
		'menu_icon' => 'dashicons-format-audio',
		'register_meta_box_cb' => null,
		'query_var' => true,
		'supports' => array( 'title', 'thumbnail', 'custom-fields' ),
		'taxonomies' => array( 'category' ),
	) );

	// Press Releases
	register_post_type( 'press_releases', array(
		'labels' => array(
			'name' => 'Press Releases',
			'singular_name' => 'Press Release',
			'all_items' => 'All Press Releases',
			'add_new_item' => 'Add new Press Release',
			'edit_item' => 'Edit Press Release',
			'new_item' => 'New Press Release',
			'view_item' => 'View Press Release',
			'view_items' => 'View Press Releases',
			'search_items' => 'Search Press Releases',
			'not_found' => 'No Press Releases found.',
			'not_found_in_trash' => 'No Press Releases found in trash.',
		),
		'description' => '',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'has_archive' => true,
		'show_in_menu' => true,
		'delete_with_user' => false,
		'show_in_rest' => true,
		'rest_base' => null,
		'rest_controller_class' => null,
		'rest_namespace' => null,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => null,
		'rewrite' => array(
			'slug' => 'press_releases',
			'with_front' => true,
		),
		'menu_position' => null,
		'menu_icon' => 'dashicons-media-document',
		'register_meta_box_cb' => null,
		'query_var' => true,
		'supports' => array( 'title', 'editor', 'thumbnail', 'custom-fields' ),
		'taxonomies' => array(  ),
	) );

	// In the News
	register_post_type( 'in_the_news', array(
		'labels' => array(
			'name' => 'In the News',
			'singular_name' => 'In the News',
			'all_items' => 'All In the News',
			'add_new_item' => 'Add new In the News',
			'edit_item' => 'Edit In the News',
			'new_item' => 'New In the News',
			'view_item' => 'View In the News',
			'view_items' => 'View In the News',
			'search_items' => 'Search In the News',
			'not_found' => 'No In the News found.',
			'not_found_in_trash' => 'No In the News found in trash.',
		),
		'description' => '',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'has_archive' => true,
		'show_in_menu' => true,
		'delete_with_user' => false,
		'show_in_rest' => true,
		'rest_base' => null,
		'rest_controller_class' => null,
		'rest_namespace' => null,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => null,
		'rewrite' => array(
			'slug' => 'in_the_news',
			'with_front' => true,
		),
		'menu_position' => null,
		'menu_icon' => 'dashicons-welcome-widgets-menus',
		'register_meta_box_cb' => null,
		'query_var' => true,
		'supports' => array( 'title', 'editor', 'thumbnail', 'custom-fields' ),
		'taxonomies' => array(  ),
	) );

	// Coupons
	register_post_type( 'coupons', array(
		'labels' => array(
			'name' => 'Coupons',
			'singular_name' => 'Coupon',
			'all_items' => 'All Coupons',
			'add_new_item' => 'Add new Coupon',
			'edit_item' => 'Edit Coupon',
			'new_item' => 'New Coupon',
			'view_item' => 'View Coupon',
			'view_items' => 'View Coupons',
			'search_items' => 'Search Coupons',
			'not_found' => 'No Coupons found.',
			'not_found_in_trash' => 'No Coupons found in trash.',
		),
		'description' => '',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'has_archive' => true,
		'show_in_menu' => true,
		'delete_with_user' => false,
		'show_in_rest' => true,
		'rest_base' => null,
		'rest_controller_class' => null,
		'rest_namespace' => null,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => null,
		'rewrite' => array(
			'slug' => 'coupons',
			'with_front' => true,
		),
		'menu_position' => null,
		'menu_icon' => 'dashicons-tickets',
		'register_meta_box_cb' => null,
		'query_var' => true,
		'supports' => array( 'title', 'thumbnail', 'excerpt', 'custom-fields' ),
		'taxonomies' => array( 'category' ),
	) );

	// Dine and Drink
	register_post_type( 'dine-drink', array(
		'labels' => array(
			'name' => 'Dine and Drink',
			'singular_name' => 'Dine and Drink',
			'all_items' => 'All Dine and Drink',
			'add_new_item' => 'Add new Dine and Drink',
			'edit_item' => 'Edit Dine and Drink',
			'new_item' => 'New Dine and Drink',
			'view_item' => 'View Dine and Drink',
			'view_items' => 'View Dine and Drink',
			'search_items' => 'Search Dine and Drink',
			'not_found' => 'No Dine and Drink found.',
			'not_found_in_trash' => 'No Dine and Drink found in trash.',
		),
		'description' => '',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'has_archive' => true,
		'show_in_menu' => true,
		'delete_with_user' => false,
		'show_in_rest' => true,
		'rest_base' => null,
		'rest_controller_class' => null,
		'rest_namespace' => null,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => null,
		'rewrite' => array(
			'slug' => 'dine-drink',
			'with_front' => true,
		),
		'menu_position' => null,
		'menu_icon' => 'dashicons-food',
		'register_meta_box_cb' => null,
		'query_var' => true,
		'supports' => array( 'title', 'thumbnail', 'custom-fields' ),
		'taxonomies' => array( 'category' ),
	) );

	// Sales and Promotions
	register_post_type( 'sales-promotions', array(
		'labels' => array(
			'name' => 'Sales and Promotions',
			'singular_name' => 'Sales and Promotions',
			'all_items' => 'All Sales and Promotions',
			'add_new_item' => 'Add new Sales and Promotions',
			'edit_item' => 'Edit Sales and Promotions',
			'new_item' => 'New Sales and Promotions',
			'view_item' => 'View Sales and Promotions',
			'view_items' => 'View Sales and Promotions',
			'search_items' => 'Search Sales and Promotions',
			'not_found' => 'No Sales and Promotions found.',
			'not_found_in_trash' => 'No Sales and Promotions found in trash.',
		),
		'description' => '',
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'has_archive' => true,
		'show_in_menu' => true,
		'delete_with_user' => false,
		'show_in_rest' => true,
		'rest_base' => null,
		'rest_controller_class' => null,
		'rest_namespace' => null,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => null,
		'rewrite' => array(
			'slug' => 'sales-promotions',
			'with_front' => true,
		),
		'menu_position' => null,
		'menu_icon' => 'dashicons-tickets-alt',
		'register_meta_box_cb' => null,
		'query_var' => true,
		'supports' => array( 'title', 'thumbnail', 'custom-fields' ),
		'taxonomies' => array( 'category' ),
	) );
}
add_action( 'init', 'mms_register_post_types', 10 );
